name: glia_leitner
description: لایتنر هوشمند گلیا کنکور
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/leitner.html
    - assets/glia_app_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/glia_app_icon.png
  adaptive_icon_background: '#081630'
  adaptive_icon_foreground: assets/glia_app_icon.png
  min_sdk_android: 21
