import 'dart:convert';
import 'dart:io';

class JsReader{JsReader(this.s);final String s;int i=0;dynamic value(){ws();if(i>=s.length)throw FormatException('unexpected eof');final c=s[i];if(c=='"'||c=="'")return str();if(c=='[')return array();if(c=='{')return object();final start=i;while(i<s.length&&!',]}\n'.contains(s[i]))i++;final x=s.substring(start,i).trim();if(x=='true')return true;if(x=='false')return false;if(x=='null')return null;final n=num.tryParse(x);return n??x;}List<dynamic>array(){i++;final a=<dynamic>[];while(true){ws();if(s[i]==']'){i++;return a;}a.add(value());ws();if(s[i]==','){i++;continue;}if(s[i]==']'){i++;return a;}throw FormatException('array');}}Map<String,dynamic>object(){i++;final m=<String,dynamic>{};while(true){ws();if(s[i]=='}'){i++;return m;}final k=value().toString();ws();if(s[i++]!=':')throw FormatException('object');m[k]=value();ws();if(s[i]==','){i++;continue;}if(s[i]=='}'){i++;return m;}throw FormatException('object');}}String str(){final q=s[i++];final b=StringBuffer();while(i<s.length){final c=s[i++];if(c==q)return b.toString();if(c=='\\'&&i<s.length){final n=s[i++];const mp={'n':'\n','r':'\r','t':'\t','b':'\b','f':'\f','"':'"',"'":"'",'\\':'\\'};if(n=='u'&&i+4<=s.length){final h=s.substring(i,i+4);b.write(String.fromCharCode(int.parse(h,radix:16)));i+=4;}else{b.write(mp[n]??n);}}else{b.write(c);}}throw FormatException('string');}void ws(){while(i<s.length&&(s[i].trim().isEmpty||s[i]=='\r'))i++;}}

String literal(String src,String name){final re=RegExp(r'(?:var|let|const)\s+'+RegExp.escape(name)+r'\s*=');final m=re.firstMatch(src);if(m==null)throw StateError('Missing $name');var i=m.end;while(i<src.length&&src[i].trim().isEmpty)i++;final open=src[i];final close=open=='['?']':'}';var depth=0;String?q;var esc=false;for(;i<src.length;i++){final c=src[i];if(q!=null){if(esc){esc=false;}else if(c=='\\'){esc=true;}else if(c==q){q=null;}continue;}if(c=='"'||c=="'"){q=c;continue;}if(c==open)depth++;if(c==close){depth--;if(depth==0)return src.substring(m.end,i+1);}}throw StateError('Unclosed $name');}

String asText(dynamic v)=>v==null?'':v.toString();
Map<String,dynamic> obj(dynamic v)=>Map<String,dynamic>.from(v as Map);
List<dynamic> list(dynamic v)=>List<dynamic>.from(v as List);

void main()async{final root=Directory.current;final html=File('${root.path}/reference/leitner_original.html').readAsStringSync();final pack=File('${root.path}/reference/persian_pack.html').readAsStringSync();
final english=<Map<String,dynamic>>[];for(final pair in [['l1Words','درس ۱'],['l2Words','درس ۲'],['l3Words','درس ۳']]){for(final e in list(JsReader(literal(html,pair[0] as String)).value())){final m=obj(e);english.add({'id':'en-${english.length}','front':asText(m['word']),'back':asText(m['meaning']),'extra':'','category':'english','lesson':pair[1],'type':'meaning'});}}
final cards=<Map<String,dynamic>>[...english];
for(final e in list(JsReader(literal(html,'irregularVerbs')).value())){final m=obj(e);cards.add({'id':'vb-${cards.length}','front':asText(m['base']),'back':asText(m['meaning']),'extra':'گذشته: ${asText(m['past'])} · اسم مفعول: ${asText(m['pp'])}','category':'verbs','lesson':'افعال بی‌قاعده','type':'verb'});}
final pv=JsReader(literal(html,'persianVocab')).value();if(pv is Map){for(final entry in pv.entries){for(final e in list(entry.value)){final m=obj(e);cards.add({'id':'fa-${cards.length}','front':asText(m['word']),'back':asText(m['meaning']),'extra':'','category':'persian','lesson':'فارسی - ${entry.key}','type':'meaning'});}}}
final ar=JsReader(literal(html,'arabicData')).value();if(ar is Map){for(final entry in ar.entries){final lesson=entry.key.toString();final d=obj(entry.value);for(final e in list(d['words']??[])){final m=obj(e);cards.add({'id':'ar-${cards.length}','front':asText(m['ar']),'back':asText(m['fa']),'extra':'','category':'arabic','lesson':'$lesson - معنی','type':'meaning'});}for(final e in list(d['synonyms']??[])){final m=obj(e);cards.add({'id':'ar-${cards.length}','front':asText(m['ar']),'back':asText(m['fa']),'extra':'مترادف','category':'arabic','lesson':'$lesson - مترادف','type':'synonym'});}for(final e in list(d['antonyms']??[])){final m=obj(e);cards.add({'id':'ar-${cards.length}','front':asText(m['ar']),'back':asText(m['fa']),'extra':'متضاد','category':'arabic','lesson':'$lesson - متضاد','type':'antonym'});}for(final e in list(d['plurals']??[])){final m=obj(e);cards.add({'id':'ar-${cards.length}','front':asText(m['singular']),'back':'جمع: ${asText(m['plural'])}','extra':'جمع مکسر','category':'arabic','lesson':'$lesson - جمع مکسر','type':'plural'});}}}
final lessons=Map<String,dynamic>.from(JsReader(literal(pack,'LESSONS_DATA')).value() as Map);final qs=<Map<String,dynamic>>[];for(final e in lessons.entries){for(final q in list(e.value)){final m=obj(q);qs.add({'id':'sp-${qs.length}','lesson':e.key,'sentence':asText(m['sentence']),'options':list(m['options']).map(asText).toList(),'correctIndex':(m['correctIndex'] as num).toInt()});}}
final vocab=Map<String,dynamic>.from(JsReader(literal(pack,'PERSIAN_VOCAB')).value() as Map);final vc=<Map<String,dynamic>>[];for(final e in vocab.entries){for(final w in list(e.value)){final m=obj(w);vc.add({'id':'pv-${vc.length}','front':asText(m['word']),'back':asText(m['meaning']),'extra':'پک فارسی','category':'persianPack','lesson':e.key,'type':'meaning'});}}
if(cards.length!=2151||qs.length!=639||vc.length!=434)throw StateError('Integrity mismatch: ${cards.length}/${qs.length}/${vc.length}');
final assets=Directory('${root.path}/assets');if(!assets.existsSync())assets.createSync(recursive:true);File('${assets.path}/generated_original_deck.json').writeAsStringSync(jsonEncode(cards));File('${assets.path}/generated_persian_pack.json').writeAsStringSync(jsonEncode({'questions':qs,'vocabCards':vc}));stdout.writeln('Generated ${cards.length} cards, ${qs.length} questions, ${vc.length} vocab cards.');}
